### ISSUE TITLE
Installation error of signatory==1.2.6.1.7.1 on GCP

### ISSUE THREAD

**Issue by L0ngD0ngG0ng** [patrick-kidger/signatory#57]
Hey, I am currently trying to run a ML piece on GCP in the latest conda environment (conda 23.3.1). Below is the output of my conda list when I am trying to install signatory: 
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
_pytorch_select           0.1                       cpu_0  
blas                      1.0                         mkl  
ca-certificates           2023.01.10           h06a4308_0  
certifi                   2022.12.7        py38h06a4308_0  
cffi                      1.15.1           py38h74dc2b5_0  
flit-core                 3.8.0            py38h06a4308_0  
intel-openmp              2019.4                      243  
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libmklml                  2019.0.5             h06a4308_0  
libstdcxx-ng              11.2.0               h1234567_1  
mkl                       2020.2                      256  
mkl-service               2.3.0            py38he904b0f_0  
mkl_fft                   1.3.0            py38h54f3939_0  
mkl_random                1.1.1            py38h0573a6f_0  
ncurses                   6.4                  h6a678d5_0  
ninja                     1.10.2               h06a4308_5  
ninja-base                1.10.2               hd09550d_5  
numpy                     1.19.2           py38h54aff64_0  
numpy-base                1.19.2           py38hfa32c7d_0  
openssl                   1.1.1t               h7f8727e_0  
pip                       23.0.1           py38h06a4308_0  
pycparser                 2.21               pyhd3eb1b0_0  
python                    3.8.3                hcff3b4d_2  
pytorch                   1.7.1           cpu_py38h6a09485_0  
readline                  8.2                  h5eee18b_0  
setuptools                65.6.3           py38h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.41.2               h5eee18b_0  
tk                        8.6.12               h1ccaba5_0  
typing-extensions         4.4.0            py38h06a4308_0  
typing_extensions         4.4.0            py38h06a4308_0  
wheel                     0.38.4           py38h06a4308_0  
xz                        5.2.10               h5eee18b_1  
zlib                      1.2.13               h5eee18b_0  

But installation command "pip install signatory==1.2.6.1.7.1 --no-cache-dir --force-reinstall" gives me this error: 
Collecting signatory==1.2.6.1.7.1
  Downloading signatory-1.2.6.1.7.1.tar.gz (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 4.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: signatory
  Building wheel for signatory (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [67 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/signatory
      copying src/signatory/path.py -> build/lib.linux-x86_64-cpython-38/signatory
      copying src/signatory/__init__.py -> build/lib.linux-x86_64-cpython-38/signatory
      copying src/signatory/signature_module.py -> build/lib.linux-x86_64-cpython-38/signatory
      copying src/signatory/unstable.py -> build/lib.linux-x86_64-cpython-38/signatory
      copying src/signatory/augment.py -> build/lib.linux-x86_64-cpython-38/signatory
      copying src/signatory/deprecated.py -> build/lib.linux-x86_64-cpython-38/signatory
      copying src/signatory/utility.py -> build/lib.linux-x86_64-cpython-38/signatory
      copying src/signatory/logsignature_module.py -> build/lib.linux-x86_64-cpython-38/signatory
      copying src/signatory/signature_inversion_module.py -> build/lib.linux-x86_64-cpython-38/signatory
      copying src/signatory/impl.py -> build/lib.linux-x86_64-cpython-38/signatory
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ob03iova/signatory_d1c497b804c54b7f800995e505ded1cb/setup.py", line 53, in <module>
          setuptools.setup(name=metadata.project,
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 361, in build_extensions
          self._check_abi()
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 699, in _check_abi
          check_compiler_abi_compatibility(compiler)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 265, in check_compiler_abi_compatibility
          if not check_compiler_ok_for_platform(compiler):
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 225, in check_compiler_ok_for_platform
          which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/subprocess.py", line 411, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/subprocess.py", line 512, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for signatory
  Running setup.py clean for signatory
Failed to build signatory
Installing collected packages: signatory
  Running setup.py install for signatory ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for signatory did not run successfully.
  │ exit code: 1
  ╰─> [71 lines of output]
      running install
      /home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/signatory
      copying src/signatory/path.py -> build/lib.linux-x86_64-cpython-38/signatory
      copying src/signatory/__init__.py -> build/lib.linux-x86_64-cpython-38/signatory
      copying src/signatory/signature_module.py -> build/lib.linux-x86_64-cpython-38/signatory
      copying src/signatory/unstable.py -> build/lib.linux-x86_64-cpython-38/signatory
      copying src/signatory/augment.py -> build/lib.linux-x86_64-cpython-38/signatory
      copying src/signatory/deprecated.py -> build/lib.linux-x86_64-cpython-38/signatory
      copying src/signatory/utility.py -> build/lib.linux-x86_64-cpython-38/signatory
      copying src/signatory/logsignature_module.py -> build/lib.linux-x86_64-cpython-38/signatory
      copying src/signatory/signature_inversion_module.py -> build/lib.linux-x86_64-cpython-38/signatory
      copying src/signatory/impl.py -> build/lib.linux-x86_64-cpython-38/signatory
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ob03iova/signatory_d1c497b804c54b7f800995e505ded1cb/setup.py", line 53, in <module>
          setuptools.setup(name=metadata.project,
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 361, in build_extensions
          self._check_abi()
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 699, in _check_abi
          check_compiler_abi_compatibility(compiler)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 265, in check_compiler_abi_compatibility
          if not check_compiler_ok_for_platform(compiler):
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 225, in check_compiler_ok_for_platform
          which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/subprocess.py", line 411, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/home/yg2911/anaconda3/envs/py383/lib/python3.8/subprocess.py", line 512, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> signatory

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

I have tried on my own device and it exhibits the same behavior. Any solutions? Thanks so much!

**Comment by patrick-kidger** [comment]
Looks like you don't have a C++ toolchain installed. (I.e. you don't have a C++ compiler installed.)

Assuming you're on Linux, that's relatively unusual, but not unheard of. Try installing gcc.
